package eu.bbmri_eric.quality.server.user;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.Table;
import java.util.Collections;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * User entity representing a user account in the system. Follows domain-driven design principles
 * with proper encapsulation.
 */
@Entity
@Table(name = "user_account")
class User {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private final Long id;

  private final String username;
  private String password;
  private String agentId;

  @ElementCollection(fetch = FetchType.EAGER)
  @CollectionTable(name = "user_roles", joinColumns = @JoinColumn(name = "user_id"))
  @Column(name = "role")
  @Enumerated(EnumType.STRING)
  private Set<UserRole> roles = new HashSet<>();

  /**
   * Constructor for creating a new user.
   *
   * @param username the username, must not be null
   * @param password the password, must not be null
   */
  protected User(String username, String password) {
    this.id = null; // Will be generated by JPA
    this.username = Objects.requireNonNull(username, "Username cannot be null");
    this.password = Objects.requireNonNull(password, "Password cannot be null");
  }

  /**
   * Constructor for creating a new user.
   *
   * @param username the username, must not be null
   * @param password the password, must not be null
   */
  protected User(String username, String password, String agentId) {
    this.id = null; // Will be generated by JPA
    this.username = Objects.requireNonNull(username, "Username cannot be null");
    this.password = Objects.requireNonNull(password, "Password cannot be null");
    this.agentId = agentId;
  }

  /** Default constructor for JPA. */
  protected User() {
    this.id = null;
    this.username = null;
    this.password = null;
  }

  public String getUsername() {
    return username;
  }

  public String getPassword() {
    return password;
  }

  public Long getId() {
    return id;
  }

  public Set<UserRole> getRoles() {
    return Collections.unmodifiableSet(roles);
  }

  /**
   * Updates the user's password.
   *
   * @param newPassword the new password, must not be null
   */
  public void updatePassword(String newPassword) {
    this.password = Objects.requireNonNull(newPassword, "Password cannot be null");
  }

  public void addRole(UserRole role) {
    roles.add(role);
  }

  public void removeRole(UserRole role) {
    roles.remove(role);
  }

  public boolean hasRole(UserRole role) {
    return roles.contains(role);
  }

  public String getAgentId() {
    return agentId;
  }

  public void setAgentId(String agentId) {
    this.agentId = agentId;
  }

  @Override
  public boolean equals(Object o) {
    if (o == null || getClass() != o.getClass()) return false;
    User user = (User) o;
    return Objects.equals(id, user.id)
        && Objects.equals(username, user.username)
        && Objects.equals(password, user.password)
        && Objects.equals(agentId, user.agentId)
        && Objects.equals(roles, user.roles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, password, agentId, roles);
  }

  @Override
  public String toString() {
    return "User{username='" + username + "'}";
  }
}
