package eu.bbmri_eric.quality.server.report;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.util.List;
import org.springframework.hateoas.CollectionModel;
import org.springframework.hateoas.EntityModel;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/** REST controller for managing reports. */
@RestController
@RequestMapping("/api/v1")
@Tag(name = "Reports", description = "API for managing data quality reports")
public class ReportController {

  private final ReportService reportService;
  private final ReportLinkBuilder linkBuilder;

  public ReportController(ReportService reportService, ReportLinkBuilder linkBuilder) {
    this.reportService = reportService;
    this.linkBuilder = linkBuilder;
  }

  @PostMapping("/agents/{agentId}/reports")
  @Operation(
      summary = "Create a new report",
      description = "Creates a new data quality report for an agent")
  @SecurityRequirement(name = "bearerAuth")
  public ResponseEntity<EntityModel<ReportDTO>> create(
      @PathVariable String agentId, @Valid @RequestBody ReportCreateRequest createRequest) {
    ReportDTO createdReport = reportService.create(agentId, createRequest);
    EntityModel<ReportDTO> reportModel = linkBuilder.toModel(createdReport);
    return ResponseEntity.status(HttpStatus.CREATED).body(reportModel);
  }

  @GetMapping("/reports/{id}")
  @Operation(
      summary = "Get report by ID",
      description = "Retrieves a specific report by its unique identifier")
  @SecurityRequirement(name = "bearerAuth")
  public ResponseEntity<EntityModel<ReportDTO>> findById(@PathVariable String id) {
    ReportDTO report = reportService.findById(id);
    EntityModel<ReportDTO> reportModel = linkBuilder.toModel(report);
    return ResponseEntity.ok(reportModel);
  }

  @GetMapping("/agents/{agentId}/reports")
  @Operation(
      summary = "Get reports by agent ID",
      description = "Retrieves all reports generated by a specific agent")
  @SecurityRequirement(name = "bearerAuth")
  public ResponseEntity<CollectionModel<EntityModel<ReportDTO>>> findByAgentId(
      @PathVariable String agentId) {
    List<ReportDTO> reports = reportService.findByAgentId(agentId);
    CollectionModel<EntityModel<ReportDTO>> reportsModel = linkBuilder.toCollectionModel(reports);
    return ResponseEntity.ok(reportsModel);
  }

  @GetMapping("/reports")
  @Operation(
      summary = "Get all reports",
      description = "Retrieves all reports in the system (admin only)")
  @SecurityRequirement(name = "bearerAuth")
  public ResponseEntity<CollectionModel<EntityModel<ReportDTO>>> findAll() {
    List<ReportDTO> reports = reportService.findAll();
    CollectionModel<EntityModel<ReportDTO>> reportsModel = linkBuilder.toCollectionModel(reports);
    return ResponseEntity.ok(reportsModel);
  }
}
