package eu.bbmri_eric.quality.server.report;

import java.util.List;

/** Service interface for managing reports. */
public interface ReportService {

  /**
   * Creates a new report.
   *
   * @param createRequest the report creation request
   * @return the created report as DTO
   */
  ReportDTO create(ReportCreateRequest createRequest);

  /**
   * Finds a report by its ID.
   *
   * @param id the report ID
   * @return the report DTO
   */
  ReportDTO findById(String id);

  /**
   * Finds all reports generated by a specific agent.
   *
   * @param agentId the agent ID
   * @return list of report DTOs for the specified agent
   */
  List<ReportDTO> findByAgentId(String agentId);
}
