package eu.bbmri_eric.quality.server.dataquality.domain;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDateTime;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/** Unit tests for the Report entity. */
class ReportTest {

  @Test
  @DisplayName("Should create report with auto-generated UUID")
  void createReport_shouldHaveAutoGeneratedId() {
    Report report = new Report();

    assertNotNull(report.getId());
    assertFalse(report.getId().isEmpty());
    assertTrue(
        report
            .getId()
            .matches(
                "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"));
  }

  @Test
  @DisplayName("Should create report with auto-generated timestamp")
  void createReport_shouldHaveAutoGeneratedTimestamp() {
    LocalDateTime beforeCreation = LocalDateTime.now();
    Report report = new Report();
    LocalDateTime afterCreation = LocalDateTime.now();

    assertNotNull(report.getTimestamp());
    assertTrue(
        !report.getTimestamp().isBefore(beforeCreation)
            && !report.getTimestamp().isAfter(afterCreation));
  }

  @Test
  @DisplayName("Should generate unique IDs for different reports")
  void createMultipleReports_shouldHaveUniqueIds() {
    Report report1 = new Report();
    Report report2 = new Report();

    assertNotEquals(report1.getId(), report2.getId());
  }

  @Test
  @DisplayName("Should allow updating agent ID")
  void setAgentId_shouldUpdateAgentId() {
    Report report = new Report();
    String newAgentId = "agent-456";

    report.setAgentId(newAgentId);

    assertEquals(newAgentId, report.getAgentId());
  }

  @Test
  @DisplayName("Should throw exception when setting null agent ID")
  void setAgentId_withNullAgentId_shouldThrowException() {
    Report report = new Report();

    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> report.setAgentId(null));

    assertEquals("Agent ID cannot be null or empty", exception.getMessage());
  }

  @Test
  @DisplayName("Should throw exception when setting empty agent ID")
  void setAgentId_withEmptyAgentId_shouldThrowException() {
    Report report = new Report();

    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> report.setAgentId(""));

    assertEquals("Agent ID cannot be null or empty", exception.getMessage());
  }

  @Test
  @DisplayName("Should throw exception when setting whitespace-only agent ID")
  void setAgentId_withWhitespaceAgentId_shouldThrowException() {
    Report report = new Report();

    IllegalArgumentException exception =
        assertThrows(IllegalArgumentException.class, () -> report.setAgentId("   "));

    assertEquals("Agent ID cannot be null or empty", exception.getMessage());
  }

  @Test
  @DisplayName("Should be equal to itself")
  void equals_sameObject_returnsTrue() {
    Report report = new Report();

    assertSame(report, report);
    assertEquals(report, report);
  }

  @Test
  @DisplayName("Should not be equal to null")
  void equals_nullObject_returnsFalse() {
    Report report = new Report();

    assertNotEquals(null, report);
  }

  @Test
  @DisplayName("Should not be equal to different class")
  void equals_differentClass_returnsFalse() {
    Report report = new Report();

    assertNotEquals("not a report", report);
  }

  @Test
  @DisplayName("Should not be equal to report with different ID")
  void equals_differentId_returnsFalse() {
    Report report1 = new Report();
    Report report2 = new Report();

    assertNotEquals(report1, report2);
  }

  @Test
  @DisplayName("Should have consistent hashCode")
  void hashCode_sameObject_returnsConsistentValue() {
    Report report = new Report();

    int hashCode1 = report.hashCode();
    int hashCode2 = report.hashCode();

    assertEquals(hashCode1, hashCode2);
  }
}
