package eu.bbmri_eric.quality.server.dataquality.impl;

import java.util.List;

import eu.bbmri_eric.quality.server.dataquality.domain.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/** Repository interface for Report entity. */
@Repository
public interface ReportRepository extends JpaRepository<Report, String> {

  /**
   * Finds all reports generated by a specific agent.
   *
   * @param agentId the ID of the agent
   * @return list of reports for the specified agent
   */
  List<Report> findByAgentId(String agentId);
}
